const quotes = [
  "Believe in yourself.",
  "Progress over perfection.",
  "Small steps matter.",
  "Consistency creates results.",
  "Dreams need action.",
  "Focus fuels success.",
  "Patience builds strength.",
  "Start where you are.",
  "Discipline beats motivation.",
  "Learning never stops.",
  "Action creates clarity.",
  "Effort compounds daily.",
  "Courage comes first.",
  "Momentum changes everything.",
  "Growth feels uncomfortable.",
  "Your future starts today.",
  "Simple is powerful.",
  "Commit and continue.",
  "Progress is progress.",
  "Direction beats speed.",
  "Keep moving forward.",
  "Failure teaches wisdom.",
  "Time reveals truth.",
  "Hard work pays off.",
  "Confidence is built.",
  "Dream big, start small.",
  "Persistence wins.",
  "Mindset matters most.",
  "Results follow habits.",
  "Stay curious.",
  "Adapt and evolve.",
  "Trust the process.",
  "Create your path.",
  "Work with purpose.",
  "Believe, then act.",
  "Stay consistent.",
  "Energy follows focus.",
  "Learn from mistakes.",
  "Be relentlessly kind.",
  "Stay hungry.",
  "Push past fear.",
  "Create daily.",
  "Think long-term.",
  "Take responsibility.",
  "Be intentional.",
  "Stay disciplined.",
  "Show up daily.",
  "Growth takes time.",
  "Build momentum.",
  "Choose progress.",
  "Act with courage.",
  "Value your time.",
  "Make it happen.",
  "Do the work.",
  "Stay resilient.",
  "Believe again.",
  "Create consistency.",
  "Focus deeply.",
  "Simplify often.",
  "Challenge yourself.",
  "Never stop learning.",
  "Trust yourself.",
  "Stay adaptable.",
  "Grow intentionally.",
  "Act despite fear.",
  "Build daily habits.",
  "Success is earned.",
  "Stay patient.",
  "Progress compounds.",
  "Learn continuously.",
  "Move with purpose.",
  "Create momentum.",
  "Embrace challenges.",
  "Start today.",
  "Choose discipline.",
  "Think clearly.",
  "Execute relentlessly.",
  "Believe always.",
  "Stay focused.",
  "Grow stronger.",
  "Keep building.",
  "Act boldly.",
  "Move forward.",
  "Finish strong.",
  "Stay committed.",
  "Build confidence.",
  "Take action.",
  "Be consistent.",
  "Never quit.",
  "Stay sharp.",
  "Win daily.",
  "Keep improving."
];

const button =  document.querySelector("button");
const quote = document.querySelector('h1');

button.addEventListener('click',()=>{
    const index = Math.floor(Math.random()*20);

    quote.textContent = quotes[index];
});

